In [2]:
import cdt
import igraph as ig
import networkx as nx

/home/abc/miniconda3/envs/media/lib/python3.7/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Detecting 2 CUDA device(s).


In [6]:
data, graph = cdt.data.load_dataset('sachs')
print(data.shape)
# 输出graph的类型
print(type(graph))


(7466, 11)
<class 'networkx.classes.digraph.DiGraph'>


In [7]:
l = list(graph.nodes())
print(l)

['PIP2', 'PKC', 'plcg', 'PIP3', 'pjnk', 'P38', 'PKA', 'praf', 'pmek', 'p44/42', 'pakts473']


In [9]:
a = nx.adj_matrix(graph).todense()
print(a)
print(type(a))

[[0 1 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 1 1 0 1 1 0 0]
 [1 1 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 1 0 1 1 1 1]
 [0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]]
<class 'numpy.matrix'>


adj_matrix is deprecated and will be removed in version 3.0.
Use `adjacency_matrix` instead

